# Generated by Django 5.1 on 2025-12-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Clase CSS para icono (ej: fa-wifi)", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Espacio"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Capacidad de personas"),
                ),
                (
                    "size_sqm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Tamaño (m2)"
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("latitude", models.FloatField(help_text="Latitud para el mapa")),
                ("longitude", models.FloatField(help_text="Longitud para el mapa")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        to="venues.amenity",
                        verbose_name="Instalaciones/Comodidades",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="venues/")),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Es la foto principal?"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="venues.venue",
                    ),
                ),
            ],
        ),
    ]
