# Generated by Django 5.1 on 2025-12-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="ar_model",
            field=models.FileField(
                blank=True,
                help_text="Sube aquí tu archivo .glb para Realidad Aumentada",
                null=True,
                upload_to="venues/3d/",
                verbose_name="Modelo 3D (.glb)",
            ),
        ),
    ]
