# Generated by Django 5.1 on 2025-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Ej: Boda, Conferencia, Cumpleaños", max_length=100
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Inicio del Evento")),
                ("end_time", models.DateTimeField(verbose_name="Fin del Evento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Aprobación"),
                            ("CONFIRMED", "Confirmada"),
                            ("COMPLETED", "Finalizada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True, help_text="Notas internas del trabajador", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
